apiVersion: v1
kind: ConfigMap
metadata:
  name: rocketmq-cm
data:
  broker.conf: |-
    brokerClusterName = DefaultCluster
    brokerName = broker-a
    brokerId = 0
    defaultTopicQueueNums = 4
    autoCreateTopicEnable = true
    autoCreateSubscriptionGroup = true
    deleteWhen = 04
    fileReservedTime = 48
    brokerRole = ASYNC_MASTER
    flushDiskType = ASYNC_FLUSH
