apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-cm
data:
  my.cnf: |
      [mysqld]
      skip-host-cache
      skip-name-resolve
      datadir=/var/lib/mysql
      socket=/var/run/mysqld/mysqld.sock
      secure-file-priv=/var/lib/mysql-files
      user=mysql        
      symbolic-links=0        
      pid-file=/var/run/mysqld/mysqld.pid
      character-set-server=utf8mb4
      collation-server=utf8mb4_unicode_ci
      lower-case-table-names=1
      max_connections=2000
      max_allowed_packet=30M
      bulk_insert_buffer_size=32M
      innodb_log_buffer_size=64M
      innodb_buffer_pool_size=64M
      group_concat_max_len=300000
      server-id=1
      binlog-ignore-db=mysql
      binlog-ignore-db=information_schema
      binlog-ignore-db=performance_schema
      binlog-ignore-db=sys
      log-error=/var/lib/mysql-logs/mysqld.log
      log_bin=/var/lib/mysql-logs/mysql_bin
      log_bin_index=/var/lib/mysql-logs/mysql-bin.index
      expire_logs_days=7
      max_binlog_size=200M
      sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
      [client]
      socket=/var/run/mysqld/mysqld.sock        
      !includedir /etc/mysql/conf.d/
      !includedir /etc/mysql/mysql.conf.d/
      default-character-set=utf8mb4
      [mysql]
      default-character-set=utf8mb4
