apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    k8s.kuboard.cn/name: nacos
  name: nacos
  namespace: dev
spec:
  ports:
    - name: http-8848
      nodePort: 30008
      port: 8848
      protocol: TCP
      targetPort: 8848
    - name: http-9848
      nodePort: 31008
      port: 9848
      protocol: TCP
      targetPort: 9848
  selector:
    app: nacos
  type: NodePort
