apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 10
  name: mall-demo
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mall-demo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mall-demo
    spec:
      containers:
        - image: 'registry.cn-shenzhen.aliyuncs.com/ttprod/mall-demo:v7'
          imagePullPolicy: Always
          name: mall-demo
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: "2000m"
              memory: "2048Mi"
            requests:
              cpu: "500m"
              memory: "1024Mi"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt/skywalking/agent
              name: skywalking-agent
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: rep-secret
      volumes:
        - emptyDir: {}
          name: skywalking-agent
      initContainers:
        - command:
            - sh
            - '-c'
            - >-
              set -ex ; mkdir -p /skywalking/agent ; cp -r /skywalking-agent/* /skywalking/agent ;
          image: 'registry.cn-shenzhen.aliyuncs.com/ttprod/skywalking-agent:9.0.0'
          imagePullPolicy: IfNotPresent
          name: init-skywalking-agent
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /skywalking/agent
              name: skywalking-agent
