apiVersion: v1
kind: Service
metadata:
  name: mall-front
spec:
  ports:
    - nodePort: 30070
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: mall-front
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 10
  name: mall-front
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mall-front
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mall-front
    spec:
      containers:
        - image: 'registry.cn-shenzhen.aliyuncs.com/demo/mall-front:v6'
          imagePullPolicy: Always
          name: mall-front
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: rep-secret
