apiVersion: v1
kind: Service
metadata:
  labels:
    app: skywalking
    component: ui
    release: skywalking
  name: skywalking-ui
spec:
  ports:
  - port: 80
    nodePort: 30018
    protocol: TCP
    targetPort: 8080
  selector:
    app: skywalking
    component: ui
    release: skywalking
  sessionAffinity: None
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: skywalking
    component: ui
    release: skywalking
  name: skywalking-ui
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: skywalking
      component: ui
      release: skywalking
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: skywalking
        component: ui
        release: skywalking
    spec:
      containers:
      - env:
        - name: TZ
          value: "Asia/Shanghai"
        - name: SW_OAP_ADDRESS
          value: http://skywalking-oap:12800
        image: skywalking.docker.scarf.sh/apache/skywalking-ui:9.2.0
        imagePullPolicy: IfNotPresent
        name: ui
        ports:
        - containerPort: 8080
          name: page
          protocol: TCP
        resources:
          limits:
            cpu: "1000m"
            memory: "1024Mi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
