apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-cm
data:
  mongodb.conf: |
    dbpath=/mongodb/data
    logpath=/mongodb/mongodb.log
    pidfilepath=/mongodb/master.pid
    directoryperdb=true
    logappend=true
    bind_ip=0.0.0.0
    port=27017
    auth=true
